== 유저

=== 유저 권한 부여

operation::member-controller-test/add-member-topic-permission[snippets='http-request,http-response']

=== 유저 권한 삭제

operation::member-controller-test/delete-member-topic-permission[snippets='http-request,http-response']

=== 토픽에 권한을 가진 유저 목록 조회

operation::member-controller-test/find-member-topic-permission-all[snippets='http-request,http-response']

=== 토픽에 권한을 가진 유저 단일 조회

operation::member-controller-test/find-member-topic-permission-by-id[snippets='http-request,http-response']

=== 유저 생성

operation::member-controller-test/add[snippets='http-request,http-response']

=== 유저 목록 조회

operation::member-controller-test/find-all-member[snippets='http-request,http-response']

=== 유저 단일 조회

operation::member-controller-test/find-member-by-id[snippets='http-request,http-response']

=== 유저가 만든 핀 조회

operation::member-controller-test/find-pins-by-member[snippets='http-request,http-response']

=== 유저가 만든 토픽 조회

operation::member-controller-test/find-topics-by-member[snippets='http-request,http-response']

=== 토픽을 유저의 즐겨찾기에 추가

operation::member-controller-test/add-topic-in-bookmark[snippets='http-request,http-response']

=== 유저의 토픽 즐겨찾기 목록 조회

operation::member-controller-test/find-topics-in-bookmark[snippets='http-request,http-response']
