== 토픽

=== 토픽 전체 목록 조회

operation::topic-controller-test/find-all[snippets='http-request,http-response']

=== 최신 토픽 목록 조회

operation::topic-controller-test/find-all-by-order-by-updated-at-desc[snippets='http-request,http-response']

=== 인기 급상승 토픽 목록 조회 (즐겨찾기 기준)

operation::topic-controller-test/find-all-best-topics[snippets='http-request,http-response']

=== 멤버별 토픽 목록 조회

operation::topic-controller-test/find-all-topics-by-member-id[snippets='http-request,http-response']

=== 주변 인기 토픽 목록 조회 (핀 개수 기준)

operation::location-controller-test/find-nearby-topics-sorted-by-pin-count[snippets='http-request,http-response']

=== 토픽 상세 조회

operation::topic-controller-test/find-by-id[snippets='http-request,http-response']

=== 토픽 생성

operation::topic-controller-test/create[snippets='http-request,http-response']

=== 토픽 병합

operation::topic-controller-test/merge-and-create[snippets='http-request,http-response']

=== 토픽에 핀 추가

operation::topic-controller-test/copy-pin[snippets='http-request,http-response']

=== 토픽 수정

operation::topic-controller-test/update[snippets='http-request,http-response']

=== 토픽 삭제

operation::topic-controller-test/delete[snippets='http-request,http-response']

