DROP TABLE IF EXISTS PIN;
DROP TABLE IF EXISTS TOPIC;
DROP TABLE IF EXISTS LOCATION;

create table location
(
    latitude            numeric(18, 15),
    longitude           numeric(18, 15),
    created_at          timestamp(6),
    id                  bigint generated by default as identity,
    updated_at          timestamp(6),
    legal_dong_code     varchar(255) not null,
    parcel_base_address varchar(255) not null,
    road_base_address   varchar(255) not null,
    primary key (id)
);

create table topic
(
    is_deleted  boolean default false not null,
    created_at  timestamp(6),
    id          bigint generated by default as identity,
    updated_at  timestamp(6),
    name        varchar(20)           not null,
    description clob                  not null,
    primary key (id)
);

create table pin
(
    is_deleted  boolean default false not null,
    created_at  timestamp(6),
    id          bigint generated by default as identity,
    location_id bigint                not null,
    topic_id    bigint                not null,
    updated_at  timestamp(6),
    name        varchar(50)           not null,
    description clob                  not null,
    primary key (id)
);


-- Location
insert into LOCATION (parcel_base_address, road_base_address, latitude, longitude, legal_dong_code)
values ('지번 주소1', '도로명 주소1', 0, 0, '법정동1');

insert into LOCATION (parcel_base_address, road_base_address, latitude, longitude, legal_dong_code)
values ('지번 주소2', '도로명 주소2', 0, 0, '법정동2');

-- Topic
insert into TOPIC (name, description, is_deleted)
values ('준팍의 또간집', '준팍이 두번 이상 간 집', false);

insert into TOPIC (name, description, is_deleted)
values ('도이의 또간집', '도이가 두번 이상 간 집', false);

insert into TOPIC (name, description, is_deleted)
values ('패트릭의 또간집', '패트릭이 두번 이상 간 집', false);


-- Pin
-- 준팍 핀 1개
insert into PIN (name, description, location_id, topic_id)
VALUES ('준팍핀', '첫번째 핀', 2L, 1L);

-- 도이 핀 2개
insert into PIN (name, description, location_id, topic_id)
VALUES ('도이핀', '두번째 핀', 2L, 2L);

insert into PIN (name, description, location_id, topic_id)
VALUES ('도이핀', '세번째 핀', 2L, 2L);

-- 패트릭 핀 3개
insert into PIN (name, description, location_id, topic_id)
VALUES ('패트릭핀', '네번째 핀', 2L, 3L);

insert into PIN (name, description, location_id, topic_id)
VALUES ('패트릭핀', '다섯번째 핀', 2L, 3L);

insert into PIN (name, description, location_id, topic_id)
VALUES ('패트릭핀', '여섯번째 핀', 2L, 3L);
