spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USER_NAME}
    password: ${MYSQL_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

oauth:
  kakao:
    client_id: ${OAUTH_KAKAO_CLIENT_ID}
    redirect_uri: ${OAUTH_KAKAO_REDIRECT_URI}
    client_secret: ${OAUTH_KAKAO_CLIENT_SECRET}
    scope: ${OAUTH_KAKAO_SCOPE}

security:
  jwt:
    token:
      secret-key: ${JWT_TOKEN_SECRET_KEY}
      expire-length: ${JWT_TOKEN_EXPIRE_LENGTH}
