spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USER_NAME}
    password: ${MYSQL_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

logging:
  file:
    # jar 파일 실행 시, jar 파일과 동일한 디렉토리 내 log 디렉토리에 생성됨
    path: /home/ubuntu/backend/build/log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %msg %n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %msg %n"

oauth:
  kakao:
    client_id: ${OAUTH_KAKAO_CLIENT_ID}
    redirect_uri: ${OAUTH_KAKAO_REDIRECT_URI}
    client_secret: ${OAUTH_KAKAO_CLIENT_SECRET}
    scope: ${OAUTH_KAKAO_SCOPE}
security:
  jwt:
    token:
      secret-key: ${JWT_TOKEN_SECRET_KEY}
      expire-length: ${JWT_TOKEN_EXPIRE_LENGTH}

