spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:mapbefine;MODE=MySQL
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

oauth:
  kakao:
    client_id: ${OAUTH_KAKAO_CLIENT_ID}
    redirect_uri: ${OAUTH_KAKAO_REDIRECT_URI}
    client_secret: ${OAUTH_KAKAO_CLIENT_SECRET}
    scope: ${OAUTH_KAKAO_SCOPE}

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expire-length: ${JWT_EXPIRE_LENGTH}
