name: Backend CI For Test Validation

on:
  workflow_dispatch:
  
  pull_request:
    branches: [ main, develop-BE-2 ]
    paths: backend/**

permissions:
  pull-requests: write
  checks: write
  contents: write
  
jobs:
  build-and-comment:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 테스트 환경변수 설정
        run: |
          echo "TEST_JWT_SECRET_KEY=${{ secrets.TEST_JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "TEST_JWT_EXPIRE_LENGTH=${{ secrets.TEST_JWT_EXPIRE_LENGTH }}" >> $GITHUB_ENV

      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew
        working-directory: backend

      - name: Gradle build 시작
        run: ./gradlew clean build
        working-directory: backend

      - name: 테스트 결과를 PR에 코멘트로 등록합니다
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: 'backend/build/test-results/test/TEST-*.xml'

      - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트를 등록합니다
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}
