name: Frontend production CI/CD

on:
  workflow_dispatch:

  pull_request:
    branches: [ develop ]
    types: [closed]
    paths: frontend/**

permissions:
  contents: read

jobs:
  build-and-upload:
    if: github.event.pull_request.merged

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install npm
        run: npm install --force

      - name: grant excute access
        run: chmod +x npm

      - name: Build project
        run: npm run build

      - name: upload to artifact
        uses: actions/upload-artifact@v3
        with:
          name: FrontendApplication
          path: frontend/dist/main.bundle.js

    deploy:
      runs-on: [ self-hosted, prod]
      needs: build-and-upload

      if: github.event.pull_request.merged

      steps:
        - name: delete old js file
          run: rm -rf /home/ubuntu/frontend/build/*.js

        - name: download js file from artifact
          uses: actions/download-artifact@v3
          with:
            name: FrontendApplication
            path: /home/ubuntu/frontend/build/

        - name: deploy
          runs: /home/ubuntu/frontend/build/deploy.sh

        - name: send slack message

          uses: 8398a7/action-slack@v3
          with:
            mention: 'here'
            if_mention: always
            status: ${{ job.status }}
            fields: workflow,job,commit,message,ref,author,took
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          if: always()
