name: Frontend CI For Test Validation

on:
  # pull request open과 reopen 시 실행한다.
  pull_request:
    branches: [main, develop]
    paths: frontend/**

defaults:
  run:
    working-directory: ./frontend

jobs:
  jest:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install node modules
        run: npm install

      - name: Run Jest test
        run: npm run test

      - name: Start npm
        run: npm run dev

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          start: npm run cypress
